name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode.app
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: swift test -v
